### ISSUE TITLE
Multi-instance support

### ISSUE THREAD

**Issue by mezantrop** [TimvanDijkNL/minecraft_rc_script#1]
This is not an issue/bugreport, just a request for an optional feature to run several Minecraft instances on different ports.

**Comment by TimvanDijkNL** [comment]
For that I would recommend using [sysutils/py-supervisor](https://www.freshports.org/sysutils/py-supervisor/) instead; Which allows you to define multiple instances with their own names.

**Comment by TimvanDijkNL** [comment]
( closed it before typing reply )

**Comment by TimvanDijkNL** [comment]
For Multi-instance, I would recommend using [sysutils/py-supervisor](https://www.freshports.org/sysutils/py-supervisor/) instead; Which allows you to define multiple instances with their own names.
